### ISSUE TITLE
Add support for Karapace (aiven) schema registry

### ISSUE THREAD

**Issue by Boniker** [redpanda-data/console#1105]
**Error:**
`
{"level":"error","ts":"", "msg":"Sending REST error","route":"/api/schema-registry/mode","method":"GET","status_code":502,"remote_address":"127.0.0.1:35678","public_error":"Failed to retrieve schema registry mode from the schema registry: get mode request failed: Status code 404","error":"get mode request failed: Status code 404"}
`

**Configurations:**
```
kafka:
  brokers: <broker>:9096
  sasl:
    enabled: true
    mechanism: <SSL/PLAINTEXT>
    password: <password>
    username: <username>
  schemaRegistry:
    enabled: true
    password: <password>
    urls:
    - http://<path_to_k8s_service>:8081/
    username: <username>
```

**Product:** console
**Console chart version:** v0.7.20 (with problem, last version without problem: v0.7.15)
**Kafka security.protocol:** SASL_SSL
**SchemaRegistry:** karapace (aiven)
