### ISSUE TITLE
How to set up security protocol SASL_PLAINTEXT ?

### ISSUE THREAD

**Issue by arman-sydikov** [redpanda-data/console#1269]
In the following documentation which environment variable should we use to set up security protocol SASL_PLAINTEXT ?
https://github.com/redpanda-data/console/blob/master/docs/config/console.yaml

Currently we use these environment variable variables for connection to kafka

- KAFKA_BROKERS
- KAFKA_SASL_MECHANISM
- KAFKA_SASL_USERNAME
- KAFKA_SASL_PASSWORD

the only property left is SASL_PLAINTEXT

**Comment by arman-sydikov** [comment]
fixed

**Comment by weeco** [comment]
@manodupont See here: https://github.com/redpanda-data/console/blob/d7db4874bfe82735c111a71b55baea3b26f72085/docs/config/console.yaml#L34-L38

Just use mechanism: PLAIN instead. If you want to use environment variables instead of using the YAML config make sure to read this: https://github.com/redpanda-data/console/blob/d7db4874bfe82735c111a71b55baea3b26f72085/docs/config/console.yaml#L2-L25

**Comment by manodupont** [comment]
@weeco  Thanks for this quick reply.

It doesn't seem to work actually.

Here is a snippet of docker-compose.yml

```
version: '3.5'

services:
  kafka:
    image: 'bitnami/kafka:3.7.0-debian-12-r7'
    ports:
      - "9092:9092"  # Exposing SASL_PLAINTEXT port
    environment:
      KAFKA_CFG_NODE_ID: '1'
      KAFKA_CFG_BROKER_ID: '1'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@127.0.0.1:9093'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_LISTENERS: 'CONTROLLER://:9093,INTERNAL://:9094,SASL_PLAINTEXT://:9092'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'SASL_PLAINTEXT://127.0.0.1:9092,INTERNAL://kafka:9094'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: 'PLAIN'
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'PLAIN'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CFG_LISTENER_NAME_SASL_PLAINTEXT_PLAIN_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret" user_admin="admin-secret";'

```

I try to connect redpanda using this
```
docker run -p 8080:8080 -e KAFKA_BROKERS=localhost:9092 -e KAFKA_SASL_MECHANISM='PLAIN' -e KAFKA_SASL_ENABLED=true -e KAFKA_SASL_USERNAME='admin' -e KAFKA_SASL_PASSWORD='admin-secret' docker.redpanda.com/redpandadata/console:latest
```

Its not working. I get this error
```
{"level":"warn","ts":"2024-06-11T15:32:14.922Z","msg":"Failed to test Kafka connection, going to retry in 1s","remaining_retries":5}
{"level":"info","ts":"2024-06-11T15:32:15.922Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}
{"level":"warn","ts":"2024-06-11T15:32:15.923Z","logger":"kafka_client","msg":"unable to open connection to broker","addr":"localhost:9092","broker":"seed_0","err":"dial tcp 127.0.0.1:9092: connect: connection refused"}
{"level":"warn","ts":"2024-06-11T15:32:15.923Z","msg":"Failed to test Kafka connection, going to retry in 2s","remaining_retries":4}
```


I don't understand why, a side application that I am running locally, using KafkaJS, is able to connect using this configuration
```json
{
    consumerGroupId: 'test',
    brokers: 'localhost:9092',
    sasl: {
        mechanism: 'plain', // ['plain','scram-sha-256','scram-sha-512']
	username: 'admin',
	password: 'admin-secret'
	},
}
```

I know kafkaJS is out of scope here, but its just to demonstrate that the Kafka settings in the docker-compose.yml seems for me "ok" to connect in SASL_PLAINTEXT with redpandan. Which doesn't seem to happen correctly.

What do you think ?
Thanks in advance

**Comment by arman-sydikov** [comment]
@manodupont 

If you run your app not as a docker container, it treats localhost as your computer's network, so it is able to connect to your kafka with 'localhost:9092'.

But since you are running redpanda console as a docker container, it treats localhost as container's network, kafka is not running inside of redpanda's container, that's why it is unable to connect to 'localhost:9092'.

To connect to kafka container, you need to setup its address in `KAFKA_BROKERS`. If you want to connect to host network instead, you can add `--network=host`:
```
docker run --network=host -p 8080:8080 -e KAFKA_BROKERS=localhost:9092 docker.redpanda.com/redpandadata/console:latest
```

**Comment by manodupont** [comment]
@arman-sydikov  Thanks for this quick reply but I did try and it still returns me the same errors. I have to admit that I am pretty confused. 

I did try to just docker compose everything so any network problems go away. Here is a sample:

```
version: '3.5'

services:
  kafka:
    image: 'bitnami/kafka:3.7.0-debian-12-r7'
    ports:
      - "9092:9092"  # Exposing SASL_PLAINTEXT port
    environment:
      KAFKA_CFG_NODE_ID: '1'
      KAFKA_CFG_BROKER_ID: '1'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@127.0.0.1:9093'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_LISTENERS: 'CONTROLLER://:9093,INTERNAL://:9094,SASL_PLAINTEXT://:9092'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'SASL_PLAINTEXT://127.0.0.1:9092,INTERNAL://kafka:9094'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: 'PLAIN'
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'PLAIN'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CFG_LISTENER_NAME_SASL_PLAINTEXT_PLAIN_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret" user_admin="admin-secret";'
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9094 || exit 1
      interval: 1s
      timeout: 60s
      retries: 60

  redpanda:
    image: docker.redpanda.com/redpandadata/console:latest
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_SASL_ENABLED: true
      KAFKA_SASL_USERNAME: admin
      KAFKA_SASL_PASSWORD: admin-secret

```

Using that, I still see 
```
 {"level":"warn","ts":"2024-06-11T18:01:10.346Z","logger":"kafka_client","msg":"unable to open connection to broker","addr":"127.0.0.1:9092","broker":"1","err":"dial tcp 127.0.0.1:9092: connect: connection refused"}
```

Do you agree ?
