### ISSUE TITLE
Deserialization In Redpanda Console Using Azure Dev Ops

### ISSUE THREAD

**Issue by tulde23** [redpanda-data/console#1331]
Does RP Console support AzureDevOps?  I can't seem to get my protobuf repository to clone.  It appears the SSH authentication is working, but I always receive this error:

```
failed to start kafka service: failed to start git service: failed to clone git repo: invalid reset option: object not found"}
```

My config
```
 git:
      enabled: true
      repository:
        url: git@ssh.dev.azure.com:<....>
        branch: master
      ssh:
        enabled: true
        privateKeyFilepath:<path to private key>
```
