### ISSUE TITLE
Error in RenderPreview: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by hadronzoo** [redpanda-data/console#1555]
Redpanda console is failing to render binary keys:
![image](https://github.com/user-attachments/assets/1151ca47-c3e6-4dbd-b285-9e881b4efeb5)

Here is the relevant docker compose configuration:
```yaml
services:
  redpanda:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
    image: docker.redpanda.com/redpandadata/redpanda
    container_name: redpanda
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "18081:18081"
      - "18082:18082"
      - "19092:19092"
      - "19644:9644"
    healthcheck:
      test: redpanda rpk cluster health

  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - "8080:8080"
    depends_on:
      - redpanda

volumes:
  redpanda_data:
```

There is a network error, I suspect because running in dev mode there's no authentication:
![image](https://github.com/user-attachments/assets/ab225c3d-a069-4291-9277-05ab622c7d35)

However, I'm not seeing any debug logs on the server when this error occurs.
