### ISSUE TITLE
Access to data transforms lost when a broker is unreachable

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/console#1566]
When a broker goes down, the **Data Transforms** item in the nav tree is sometimes disabled. Other times, you can click it, but the page doesn't load. When you bring the broker back up, the page is available again.

Also, it takes a while for the debug info on the **Overview** page to disappear after the broker returns online. The status changes to Running, but the debug status still says that a broker is unreachable.

https://github.com/user-attachments/assets/14341d4f-79d9-4ea0-a039-3b9fc5dc10ad

**Comment by JakeSCahill** [comment]
Thanks for the detailed response. I can get this to happen consistently (tried three times).

Here's the admin config for Console

```
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-0:9644","http://redpanda-1:9644","http://redpanda-2:9644"]
            username: superuser
            password: secretpassword
```
