### ISSUE TITLE
create user: Redpanda Admin API is not enabled (Status 503)

### ISSUE THREAD

**Issue by usernameisnull** [redpanda-data/console#1592]
when I use latest docker image, to create user, did I missed something?

docker run -p 8090:8080 -e KAFKA_BROKERS="localhost:9092" docker.redpanda.com/redpandadata/console:latest

![Image](https://github.com/user-attachments/assets/d4252b34-3d3d-4ab6-a90f-dcbdd688e3ef)

**Comment by bojand** [comment]
This functionality requires [Redpanda Admin API](https://docs.redpanda.com/current/reference/api-reference/) to be configured within the [Console configuration](https://docs.redpanda.com/current/console/config/configure-console/).

Example:
```yaml
redpanda:
  adminApi:
    enabled: true
    urls: ["http://localhost:19644"]
```
