### ISSUE TITLE
Feature Request: Pre-configure message previews for topics

### ISSUE THREAD

**Issue by clarknova9** [redpanda-data/console#168]
Currently, topic previews can only be configured in the browser.  I would like to configure topic previews in the kowl configuration file.

```
topicPreviews:
  topicName: my-topic1
    previewFields: "guid,title,description"  
    matching: ignoreCase
    multipleResults: firstResult
    resultCount: hide
```

It might make sense to combine this with #167 and instead create a general topic configuration block that would support configuring the features per topic that can only be configured in the browser today. 

- Search Filters
- Preview
- Column Settings
- start Offset
- Max Results
- Page Size
