### ISSUE TITLE
Failed to delete any topic in console v3.0.0

### ISSUE THREAD

**Issue by LeoHsiao1** [redpanda-data/console#1734]
Hello, this console is very convenient. But after upgrading to v3.0.0, I can't delete any topic.

Reproduction steps:
1. Deploy a new kafka and console using docker-compose.
    ```yml
    version: '3'
    
    services:
      kafka:
        image: apache/kafka:3.9.0
        environment:
          KAFKA_NODE_ID: 1
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
        network_mode: host
    
      console:
        image: docker.redpanda.com/redpandadata/console:v3.0.0
        environment:
          KAFKA_BROKERS: 127.0.0.1:9092
        network_mode: host
    ```
2. Create a topic:
  
  ![Image](https://github.com/user-attachments/assets/80a30636-657c-4b37-a26f-cf8c08a17a3d)
  
3. Delete this topic and an error will occur:

  ![Image](https://github.com/user-attachments/assets/26fc385c-cb96-4b02-afcb-906d4e5ae4f6)
