### ISSUE TITLE
Cannot delete records in v3.1.0

### ISSUE THREAD

**Issue by kewitschka** [redpanda-data/console#1764]
Since version 3.x it is not possible to delete records and topics anymore. 

**1. Delete records**  
The delete records button is grayed out and the tooltip says "You're not permitted to delete records on this topic".

<img width="491" alt="Image" src="https://github.com/user-attachments/assets/199ae553-ce1e-4971-9cc1-f9619d1c289c" />

**2. Delete topics**  
When the trash bin icon on a topic is clicked, the error message "Failed to delete topic - Unexpected Kafka response: No topic set in the response.

<img width="470" alt="Image" src="https://github.com/user-attachments/assets/ed4f3e60-3525-4368-8eb6-63ca484bd9db" />

```
config:
  kafka:
    brokers:
      - worker0-host:9092
      - worker1-host:9092
      - worker2-host:9092
  serde:
    protobuf:
      enabled: true
      git:
        basicAuth:
          enabled: true
          username: token
        enabled: true
        refreshInterval: 5m
        repository:
          url: https://gitlab.com/proto.git
      importPaths:
        - src/main/proto
      mappings:
        - topicName: test
          valueProtoType: Test
```
