### ISSUE TITLE
v3 console connection to redpanda reporting errors

### ISSUE THREAD

**Issue by keven1024** [redpanda-data/console#1797]
If I use the v2 image, I can connect to redpanda

```
// v2 
docker run -p 8080:8080 -e KAFKA_BROKERS=192.168.100.5:9092 docker.redpanda.com/redpandadata/console:latest 
```
Error if I'm using v3 console image 

```
// v3 
docker run -p 8080:8080 -e KAFKA_BROKERS=192.168.100.5:9092 docker.redpanda.com/redpandadata/console:3.1.1
```
I tried various parameters like 
- PLAINTEXT://192.168.100.5:9092 
- host.docker.internal:9092 
- http://192.168.100.5:9092 
- 192.168.100.5:9092

```log
INF ts=2025-06-05T09:34:46.958Z msg=connecting to Kafka seed brokers, trying to fetch cluster metadata seed_brokers=["PLAINTEXT://192.168.100.5:9092"]

WRN ts=2025-06-05T09:34:46.958Z logger=kafka_client msg=unable to open connection to broker addr=[PLAINTEXT://192.168.100.5:9092]:9092 broker=seed_0 err=dial tcp: lookup PLAINTEXT://192.168.100.5:9092: no such host

WRN ts=2025-06-05T09:34:46.958Z msg=failed to test Kafka connection, going to retry in 16s remaining_retries=1

fatal ts=2025-06-05T09:35:02.968Z msg=failed to start console service error=failed to test kafka connectivity: failed to test kafka connection: failed to request metadata: unable to dial: dial tcp: lookup PLAINTEXT://192.168.100.5:9092: no such host
```

**Comment by weeco** [comment]
This seems to be due to invalid network connectivity. You can use these docker composes to get started: https://docs.redpanda.com/redpanda-labs/docker-compose/owl-shop/

Kafka connectivity can be tricky to grasp due to how the listeners & advertising of listeners works, see: https://rmoff.net/2018/08/02/kafka-listeners-explained/

**Comment by keven1024** [comment]
> This seems to be due to invalid network connectivity. You can use these docker composes to get started: https://docs.redpanda.com/redpanda-labs/docker-compose/owl-shop/
> 
> Kafka connectivity can be tricky to grasp due to how the listeners & advertising of listeners works, see: https://rmoff.net/2018/08/02/kafka-listeners-explained/

I have modified `redpanda.advertised_kafka_api.address` but it still doesn't work, I can connect to redpanda normally using other kafka clients

**Comment by keven1024** [comment]
other kafka clients:
<img width="1379" alt="Image" src="https://github.com/user-attachments/assets/6c0ebaac-6972-4854-a385-6d698694fa20" />

redpanda.yaml
```
redpanda:
    data_directory: /var/lib/redpanda/data
    seed_servers: []
    rpc_server:
        address: 0.0.0.0
        port: 33145
    kafka_api:
        - address: 0.0.0.0
          port: 9092
    admin:
        - address: 0.0.0.0
          port: 9644
    advertised_rpc_api:
        address: 192.168.100.5
        port: 33145
    advertised_kafka_api:
        - address: 192.168.100.5
          port: 9092
    developer_mode: true
    auto_create_topics_enabled: true
    fetch_reads_debounce_timeout: 10
    group_initial_rebalance_delay: 0
    group_topic_partitions: 3
    log_segment_size_min: 1
    storage_min_free_bytes: 10485760
    topic_partitions_per_shard: 1000
    write_caching_default: "true"
rpk:
    overprovisioned: true
    coredump_dir: /var/lib/redpanda/coredump
pandaproxy: {}
schema_registry: {}
```

redpanda-console.yml
```
kafka:
  brokers: ["http://192.168.100.5:9092"]
schemaRegistry:
  enabled: true
  urls: ["http://192.168.100.5:8081"]
redpanda:
  adminApi:
    enabled: true
    urls: ["http://192.168.100.5:9644"]
```
