### ISSUE TITLE
Protobuf validation incorrectly requires source provider when using Schema Registry

### ISSUE THREAD

**Issue by PovilasV1** [redpanda-data/console#1804]
## Bug Description

The protobuf validation logic in Redpanda Console v25.1 incorrectly requires at least one source provider (Git/FileSystem) and topic mappings to be configured, even when using Schema Registry for protobuf deserialization. This contradicts the documentation which states that Schema Registry should work without requiring additional source providers or topic mappings.

## Version & Environment

- **Redpanda Console version**: 25.1
- **Operating System**: Rocky Linux 8
- **Installation method**: Package installation

## Expected Behavior

According to the [official documentation](https://docs.redpanda.com/current/console/config/deserialization/#use-schema-registry-for-protobuf)

> If you use a Schema Registry for Protobuf deserialization, Redpanda Console can automatically fetch and use the required schemas without the need for manual topic mappings.
> 
> To configure Protobuf deserialization using Schema Registry, add the following to your configuration file:
> ```yaml
> serde:
>   protobuf:
>     enabled: true
> ```
> 
> When using Schema Registry for Protobuf, you do not need to provide specific topic mappings, as the schemas will be fetched dynamically.

## Actual Behavior

The console fails to start with the following error:

```
{"level":"fatal","msg":"failed to load yaml config","error":"config validation failed: failed to validate API config: failed to validate serde: failed to validate protobuf config: protobuf deserializer is enabled, at least one source provider for proto files must be configured"}
```

## Root Cause

The validation logic in the `Proto.Validate()` method (config/proto.go) has two problematic checks:

1. **Line 42-44**: Requires at least one source provider (Git or FileSystem) to be enabled
2. **Line 46-48**: Requires at least one topic mapping to be configured

```go
func (c *Proto) Validate() error {
	if !c.Enabled {
		return nil
	}

	if !c.Git.Enabled && !c.FileSystem.Enabled {
		return errors.New("protobuf deserializer is enabled, at least one source provider for proto files must be configured")
	}

	if len(c.Mappings) == 0 {
		return errors.New("protobuf deserializer is enabled, but no topic mappings have been configured")
	}

	return nil
}
```

## Configuration That Should Work (But Doesn't)

```yaml
kafka:
  brokers: ["localhost:9092"]

schemaRegistry:
  enabled: true
  urls: ["http://localhost:8081"]

serde:
  protobuf:
    enabled: true

server:
  listenAddress: 127.0.0.1

redpanda:
  adminApi:
    enabled: true
    urls: ["http://localhost:9644"]

kafkaConnect:
  enabled: true
  clusters:
    - name: datawarehouse
      url: http://localhost:8083
      tls:
        enabled: false
```

## Workaround

Currently, users must add dummy configurations to satisfy the validation:

```yaml
serde:
  protobuf:
    enabled: true
    mappings:
      # Dummy mapping to satisfy validation
      - topicName: "dummy-topic"
        valueProtoType: "dummy.Message"
    fileSystem:
      enabled: true
      paths: []  # Empty paths
      refreshInterval: 5m
```

## Impact

This bug prevents users from using the documented Schema Registry + Protobuf configuration in Console v25.1, forcing them to use workarounds that add unnecessary and unused configuration options.

## Steps to Reproduce

1. Configure Redpanda Console v25.1 with Schema Registry and protobuf as documented
2. Try to start the console
3. Observe the validation error

## Additional Context

This issue appears to have been introduced when protobuf configuration was moved from `kafka.protobuf` to `serde.protobuf` in v25.1, but the validation logic wasn't updated to account for the new Schema Registry integration pattern.
