### ISSUE TITLE
Several Kafka Connect pages crash browser with infinite loop

### ISSUE THREAD

**Issue by vincentjames501** [redpanda-data/console#1812]
See attached videos. 

Simply clicking on the cluster name triggers a mobx infinite loop and you can't click anything on the page. Eventually Chrome kills the tab. Note: This happens in Firefox and Safari as well.

https://github.com/user-attachments/assets/9b1a461c-1d70-4278-88f7-ed3bf9beace0

If you click on the "Connectors" tab, you can see that the components are infinitely rerendered. The page doesn't crash, but you also can't click on any of the connectors I guess due to them being rerendered so frequently.

https://github.com/user-attachments/assets/37a57271-7a30-4f68-84c9-36c11225a2d6

Currently running it as such:

```
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v3.1.1
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml && /app/console'
    volumes:
      - ./config:/tmp/config/
    environment:
      CONFIG_FILEPATH: ${CONFIG_FILEPATH:-/tmp/config.yml}
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:9092"]
        schemaRegistry:
          enabled: true
          urls: ["http://schema-registry:8085"]
        kafkaConnect:
          enabled: true
          clusters:
            - name: kafka-connect
              url: http://connect:9031
        console:
          topicDocumentation:
            enabled: true
            git:
              enabled: true
              repository:
                url: https://github.com/redpanda-data/docs
                branch: main
                baseDirectory: tests/docker-compose
    ports:
      - 9032:8080
    profiles: ["kafka"]
```
