### ISSUE TITLE
Cannot set the `kafka.schemaRegistry.urls` with environment variable (KAFKA_SCHEMAREGISTRY_URLS)

### ISSUE THREAD

**Issue by Curdled** [redpanda-data/console#225]
Hey, 

Firstly love the tool. 

I using v1.4.0 of kowl. I have managed to open and use kowl with schema registry set in the config file.

```
kafka:
  brokers:
    - localhost:9092
  schemaRegistry:
    enabled: true
    urls: [http://localhost:8081]
```

I am now trying to use the environment variables to configure the schema registry (kafka.schemaRegistry.urls: [...]) so that would be KAFKA_SCHEMAREGISTRY_URLS correct? `export KAFKA_SCHEMAREGISTRY_URLS="http://localhost:8081"`.
I have managed to use the environment variable `KAFKA_BROKERS` to set the broker (removing the brokers from the config file).

Any help would be appreciated. 

Thanks
Joe

**Comment by weeco** [comment]
Hi @Curdled , yes you'd need to export the env variables `KAFKA_SCHEMAREGISTRY_URLS` and also enable schema registry via `KAFKA_SCHEMAREGISTRY_ENABLED=TRUE`

Are you facing an issue with that? I'm unsure what problem you are facing

**Comment by Curdled** [comment]
Hey thanks for getting back to me to fast!! @weeco.

When I have the config `.yaml` file as below and the env variables `KAFKA_SCHEMAREGISTRY_URLS=http...` and `KAFKA_SCHEMAREGISTRY_ENABLED=TRUE` 
```
kafka:
  brokers:
    - localhost:9092
  schemaRegistry:
    enabled: true
  protobuf:
    enabled: true
    schemaRegistry:
      enabled: true
      refreshInterval: 1m
```
I get the response
```
$ ./kowl -config.filepath kowl.yaml
{"level":"fatal","msg":"failed to validate config","error":"failed to validate Kafka config: schema registry is enabled but no URL is configured"}
```

however removing the 3rd and 4th lines of the yaml corrects the problem.

It seems like having `kafka.schemaRegistry.enabled` without `.urls` set (in the yaml) and urls set through env variable `..._URLS` doesn't work. Which is where the confusion occurred.

Thanks, this does solve my problem.
Joe
