### ISSUE TITLE
Schema registry TLS error when Kowl => Redpanda

### ISSUE THREAD

**Issue by 4integration** [redpanda-data/console#467]
Hi,

I have been running Kowl for some time and now I wanted to upgrade to Redpanda Console.

I use this docker-compose, just changing `image`:
```
version: '2'

services:

  kowl:
    #image: 'registry.mydomain.net/builds/myteam/kowl:latest'
    image: 'registry.mydomain.net/mirrors/vectorized/console:v2.0.3'
    ports:
      - '8088:8080'
    environment:
      - CONNECT_BROKER=xxx
      - CONNECT_GROUP:xxx
      - KAFKA_BROKERS=kafka-app-test.mydomain.net:9193
      - KAFKA_TLS_ENABLED=true
      - KAFKA_TLS_CAFILEPATH=/ca.pem
      - KAFKA_TLS_CERTFILEPATH=/cert.pem
      - KAFKA_TLS_KEYFILEPATH=/encrypted.key.pem
      - KAFKA_TLS_PASSPHRASE=mypasswd
      - KAFKA_TLS_INSECURESKIPTLSVERIFY=true
      - KAFKA_SCHEMAREGISTRY_ENABLED=true
      - KAFKA_SCHEMAREGISTRY_URLS=https://kafka-schema-registry.test.mydomain.net
      - KAFKA_SCHEMAREGISTRY_USERNAME=myteam
      - KAFKA_SCHEMAREGISTRY_PASSWORD=mypasswd2
      - LOGGER_LEVEL=debug
      - CONNECT_ENABLED=true
      - CONNECT_CLUSTERS_NAME=local
      - CONNECT_CLUSTERS_URL=http://kafka_connect:8083
    volumes:
      - '/c/Users/myuid/projects/kowl/certs/ca.pem:/ca.pem'
      - '/c/Users/myuid/projects/kowl/certs/cert.pem:/cert.pem'
      - '/c/Users/myuid/projects/kowl/certs/encrypted.key.pem:/encrypted.key.pem'

```

But it fails with:
```
kowl_1              | {"level":"info","msg":"config filepath is not set, proceeding with options set from env variables and flags"}
kowl_1              | {"level":"fatal","msg":"failed to validate config","error":"failed to validate Kafka config: URL scheme is https (given URL: \"https://kafka-schema-registry.test.mydomain.net\"), but you have TLS disabled. Change URL scheme to http"}
kowl_kowl_1 exited with code 1
```
Which configuration is missing here?
