### ISSUE TITLE
Connect Error with json array

### ISSUE THREAD

**Issue by arttitb** [redpanda-data/console#519]
### Version & Environment
I run redpanda with docker
Docker image : docker.redpanda.com/vectorized/console:v2.0.3
Centos 7

### What went wrong?
I'm receiving this error when try to access connect server :
`json: cannot unmarshal array into Go value of type map[string]connect.ListConnectorsResponseExpanded`

![image](https://user-images.githubusercontent.com/96194776/200592028-179c0f99-dfe4-47f5-a439-f404947a6dce.png)

I test my docker, he can reach the kafka connect api :
```
curl "http://xx.xxx.xx.x:8084/connectors?expand=info&expand=status"

["prod-reporting-cv-ano","prod-reporting-cv","debezium-prod","prod-reporting-cv-dispositif","prod-reporting-cv2-vue","prod-reporting-pm-vue","prod-reporting-cv2-part-vue","prod-reporting-personne-de-vue","prod-reporting-offre","prod-reporting-cv-vue","prod-reporting-dispositif"]
````

This is my config file :
```
kafka:
   brokers:
      - xx.xxx.xx.x:9092
      - xx.xxx.xx.x:9092
      - xx.xxx.xx.x:9092
login:
  enabled: false
server:
   listenPort: 8080
logger:
   level: "info"
connect:
  enabled: true
  clusters:
    - name: test
      url: http://xx.xxx.xx.x:8084
      tls:
        enabled: false
  connectTimeout: 15s # used to test cluster connectivity
  readTimeout: 60s    # overall REST timeout
  requestTimeout: 6s  # timeout for REST requests
```

When I try the Redpanda API : `api/kafka-connect/connectors` :
![image](https://user-images.githubusercontent.com/96194776/200596650-e6f483e2-52af-4b6c-b921-ac462d4ed49f.png)

This is not new, previous versions return the same error..
