### ISSUE TITLE
Kerberos failure : wrong Token ID. Expected 0504, was 6030

### ISSUE THREAD

**Issue by salastrue** [redpanda-data/console#601]
Hi, 

I am trying to connect the redpanda console to a **Kafka cluster that is kerberized**. This cluster only supports two encryption types:   **_rc4-hmac_** and **_aes256-ct_s**.  

I have tried to connect with keytabs with both types of encryption and this configuration at sasl field at _config.yaml_: 

```
sasl:
    enabled: true
    mechanism: GSSAPI
    username: myuser
    gssapi:
      authType: KEYTAB_AUTH
      keyTabPath: myuser.keytab
      kerberosConfigPath: krb5.conf
      serviceName: kafka
      realm: MY.DOMAIN.CORP
      enableFast: false
      username: myuser
```

They both g**enerate the same failure**: 

```
{"level":"info","ts":"2023-01-24T15:35:18.020+0100","msg":"started Redpanda Console","version":"2.1.1","built_at":"1669902595"}
{"level":"info","ts":"2023-01-24T15:35:18.290+0100","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}
{"level":"error","ts":"2023-01-24T15:35:18.516+0100","msg":"unable to initialize sasl","source":"kafka_client","broker":"seed 0","err":"EOF"}
{"level":"error","ts":"2023-01-24T15:35:18.939+0100","msg":"unable to initialize sasl","source":"kafka_client","broker":"seed 1","err":"EOF"}
{"level":"error","ts":"2023-01-24T15:35:19.578+0100","msg":"unable to initialize sasl","source":"kafka_client","broker":"seed 2","err":"EOF"}
{"level":"error","ts":"2023-01-24T15:35:20.431+0100","msg":"unable to initialize sasl","source":"kafka_client","broker":"seed 0","err":"wrong Token ID. Expected 0504, was 6030"}
{"level":"warn","ts":"2023-01-24T15:35:20.431+0100","msg":"Failed to test Kafka connection, going to retry in 1s","remaining_retries":5}
```

I am using **_redpanda_console_2.1.1_windows_64-bit.zip_** for windows and running with _**openjdk 11 2018-09-25**_

I have seen in some related issues such as [274#issuecomment-924053396](https://github.com/colinmarc/hdfs/issues/274#issuecomment-924053396) or [1400#issue-455423482](https://github.com/Shopify/sarama/issues/1400#issue-455423482) that it may be a bug of the type of encryption supported, in this case rc4-hmac is deprecated. 

**Is this true for this case?
Is there any restriction on encryption when using kerberos?
What can the token id error mean? Is my configuration OK?**
