### ISSUE TITLE
Support proto definitions from multiple sources

### ISSUE THREAD

**Issue by dcrodman** [redpanda-data/console#606]
Hi, apologies if this exists already (I couldn't find an issue for it) but I'm trying to configure Console with protos from a couple of different sources and have realized that this doesn't really work. 

For example, take a config that looks like this:
```
kafka:
  protobuf:
    enabled: true
    filesystem:
      enabled: true
      paths:
        - /etc/console/protos
    git:
      enabled: true
      repository:
        url: https://github.com/googleapis/googleapis.git
    mappings:
      - topicName: events
        valueProtoType: my.company.Event
```

The code [here](https://github.com/redpanda-data/console/blob/master/backend/pkg/proto/service.go#L71) seems to prioritize the protos from the filesystem service and, if you also have a Git mapping like the above, it will quietly overwrite the list of files used by the proto registry with the ones from the filesystem. This effectively means that you can only have one Git source that is all-or-nothing, which may not work for a lot of people. In our case, we'd like to tie in the Google proto APIs in addition to our own internal proto definitions.

It would be really nice to be able to define multiple protobuf sources and have Console read them all and merge the results. If there's a good reason not to do this, I'd suggest mentioning in the `docs/config/console.yaml` documentation that only one of them may be defined.
