### ISSUE TITLE
Feature Request: Configure protobuf deserialization to include default values

### ISSUE THREAD

**Issue by charles-dawes** [redpanda-data/console#620]
It would be nice to be able to configure the protobuf deserialization to show the default value rather than being omitted from the message.  It is confusing for some end users reading the messages in RedPanda when fields are missing in one message, but present in another. 

I suggest a new config field within the protobuf mappings that we could use to enable this behavior at a topic level.  

```
kowl:
  config: 
    kafka:
      brokers: 
        - BROKER 1
        - BROKER 2
      tls:
        enabled: true
      protobuf:
        enabled: true
        mappings:
          - topicName: TOPICNAME
            keyProtoTye: KEY_PROTO_MESSAGE
            valueProtoType: PROTO_MESSAGE
            displayDefaultValues: true //NEW FIELD
```

I am also open to any other suggestions regarding how to implement this.  This just seemed to be the most straight forward to me.
