### ISSUE TITLE
Cluster Version: unknown custom version at least v1.0 for Kafka versions 3.4.1, 3.5.0

### ISSUE THREAD

**Issue by smatvienko-tb** [redpanda-data/console#797]
The overview page reports `unknown custom version at least v1.0` for Kafka versions 3.4.1, 3.5.0 (Kraft enabled)

![image](https://github.com/redpanda-data/console/assets/79898499/0b1cf3eb-3864-46a2-b71f-48c214911731)

**Comment by weeco** [comment]
Hey @smatvienko-tb ,
are you able to provide us a Docker compose where we can reproduce this issue? We had tested this locally and the version guessing worked fine there.

**Comment by smatvienko-tb** [comment]
Hey @weeco 


My Kubernetes deployment based on the helm chart:
```bash
helm upgrade --install tb-kafka bitnami/kafka --version 22.1.6 \
  --set kraft.clusterId=ZTUwY2U2OGVhYjdlNGMyNW \
  --set image.tag=3.4.1-debian-11-r53 \
  --set replicaCount=3 \
  --set offsetsTopicReplicationFactor=3 \
  --set transactionStateLogReplicationFactor=3 \
  --set defaultReplicationFactor=2 \
  --set metrics.kafka.enabled=true \
  --set metrics.serviceMonitor.enabled=false \
  --set persistence.size=100Gi \
  --set resources.requests.cpu=200m \
  --set resources.requests.memory=1500Mi \
  --set resources.limits.cpu=2000m \
  --set resources.limits.memory=1500Mi \
  --set podAntiAffinityPreset=hard \
  --set pdb.create=true \
  --set pdb.maxUnavailable=1 \
  --set readinessProbe.enabled=false \
  --set startupProbe.enabled=true \
  --set livenessProbe.enabled=true \
  --set image.debug=true
```
Docker compose example you can find at https://github.com/bitnami/containers/blob/main/bitnami/kafka/docker-compose-cluster.yml

My Redpanda Console manifest is:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-ui
spec:
  serviceName: kafka-ui
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: server
          imagePullPolicy: IfNotPresent
          image: redpandadata/console:v2.3.1
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 200Mi
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: KAFKA_BROKERS
              value: "tb-kafka:9092" # put your broker here
      restartPolicy: Always
```
