### ISSUE TITLE
[docker] unable to open connection to broker

### ISSUE THREAD

**Issue by nolan23** [redpanda-data/console#801]
i got this error when click on certain topics
```json
{"level":"error","ts":"2023-08-07T11:21:27.754Z","msg":"Sending REST error","route":"/api/topics","method":"GET","status_code":500,"remote_address":"192.168.96.1:63908","public_error":"Could not list topics from Kafka cluster","error":"unable to dial: dial tcp 127.0.0.1:9092: connect: connection refused"}
```
initially the red panda data console is able to connect successfully (i can open the UI in my browser). when I clicked topics menu also i can see all the topics in my kafka cluster (local). but when i click certain topics then i got above error. here is the full log
```json
{"level":"info","ts":"2023-08-07T11:21:08.477Z","msg":"started Redpanda Console","version":"v2.1.0","built_at":"1668542687"}
{"level":"info","ts":"2023-08-07T11:21:08.478Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}
{"level":"warn","ts":"2023-08-07T11:21:08.548Z","msg":"unable to open connection to broker","source":"kafka_client","addr":"127.0.0.1:9092","broker":"1","err":"dial tcp 127.0.0.1:9092: connect: connection refused"}
{"level":"info","ts":"2023-08-07T11:21:08.852Z","msg":"successfully connected to kafka cluster","advertised_broker_count":1,"topic_count":2,"controller_id":1,"kafka_version":"at least v3.3"}
{"level":"info","ts":"2023-08-07T11:21:08.852Z","msg":"creating Kafka connect HTTP clients and testing connectivity to all clusters"}
{"level":"info","ts":"2023-08-07T11:21:08.855Z","msg":"tested Kafka connect cluster connectivity","successful_clusters":0,"failed_clusters":0}
{"level":"info","ts":"2023-08-07T11:21:08.855Z","msg":"successfully create Kafka connect service"}
{"level":"info","ts":"2023-08-07T11:21:08.878Z","msg":"successfully loaded all files from filesystem into cache","source":"file_provider","loaded_files":4}
{"level":"info","ts":"2023-08-07T11:21:08.880Z","msg":"registered proto types in Console's local proto registry","registered_types":4}
{"level":"info","ts":"2023-08-07T11:21:08.880Z","msg":"checked whether all mapped proto types also exist in the local registry","types_found":3,"types_missing":0,"registered_types":4}
{"level":"warn","ts":"2023-08-07T11:21:08.891Z","msg":"unable to open connection to broker","source":"kafka_client","addr":"127.0.0.1:9092","broker":"1","err":"dial tcp 127.0.0.1:9092: connect: connection refused"}
{"level":"info","ts":"2023-08-07T11:21:09.046Z","msg":"Server listening on address","address":"[::]:8080","port":8080}
{"level":"warn","ts":"2023-08-07T11:21:09.312Z","msg":"unable to open connection to broker","source":"kafka_client","addr":"127.0.0.1:9092","broker":"1","err":"dial tcp 127.0.0.1:9092: connect: connection refused"}
{"level":"warn","ts":"2023-08-07T11:21:09.331Z","msg":"unable to open connection to broker","source":"kafka_client","addr":"127.0.0.1:9092","broker":"1","err":"dial tcp 127.0.0.1:9092: connect: connection refused"}
{"level":"warn","ts":"2023-08-07T11:21:09.334Z","msg":"unable to open connection to broker","source":"kafka_client","addr":"127.0.0.1:9092","broker":"1","err":"dial tcp 127.0.0.1:9092: connect: connection refused"}
{"level":"warn","ts":"2023-08-07T11:21:09.338Z","msg":"unable to open connection to broker","source":"kafka_client","addr":"127.0.0.1:9092","broker":"1","err":"dial tcp 127.0.0.1:9092: connect: connection refused"}
```

here is my config
```yaml
kafka:
  brokers:
    - kafka:9092
  clientId: console  
```

here is my command when running red panda data console 
```bash
docker run --network default -p 28080:8080 -v /Users/user/kafka/local/config.yaml:/etc/redpanda-console/config.yaml -v /Users/user/kafka:/etc/redpanda-console/certs -e KAFKA_BROKERS=host.docker.internal:9092 -e DEBUG=1 -e CONFIG_FILEPATH=/etc/redpanda-console/config.yaml docker.redpanda.com/vectorized/console:latest
```

and here is my docker compose 
```yaml
zookeeper:
    image: 'bitnami/zookeeper:latest'
    platform: linux/amd64
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    platform: linux/amd64
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
```

thanks in advance. for the record, it works fine when i used staging broker, but somehow got error when using local dockerized kafka
