### ISSUE TITLE
Invalid keys error getting reported for: clientId, clientSecret, scope, and tokenEndpoint in case of OAUTHBEARER

### ISSUE THREAD

**Issue by Shubham-Garg20** [redpanda-data/console#804]
Issue: I have a `console.yaml` config to connect with the broker port secured with SASL_SSL protocol. The SASL mechanism being used is OAUTHBEARER. This is how my `console.yaml` file looks:

```
kafka:
  brokers:
    - <Broker1>
    - <Broker2>
    - <Broker3>
  clientId: console
  sasl:
    enabled: true
    mechanism: "OAUTHBEARER"
    oauth:
      clientId: "<clientID>"
      clientSecret: "<clientSecret>"
      tokenEndpoint: "<endpoint_url>"
      scope: "<scope>"
  tls:
    enabled: true
    certFilepath: <file_location>
    insecureSkipTlsVerify: true
```
    
On using the above config file, it reports the following error:
{"level":"fatal","msg":"failed to load yaml config","error":"failed to unmarshal YAML config into config struct: 1 error(s) decoding:\n\n* 'kafka.sasl.oauth' has invalid keys: clientId, clientSecret, scope, tokenEndpoint"}

Strangely, it recognises the "token" key under the oauth section, but not recognising the other keys.

**Comment by weeco** [comment]
Hey @Shubham-Garg20 ,
on a first look the config looks correct. Are you using the latest Console version (v2.3.1)? The OAuth config has been extended in the last version, I assume you are using an older version which did not know yet about the clientId, clientSecret but only the token.

**Comment by Shubham-Garg20** [comment]
Hi @weeco ,
This is how my docker-compose file looks:

```
version: '2'
services:
  redpanda:
    image: vectorized/redpanda:v22.2.7
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 29092:29092

  console:
    image: docker.redpanda.com/vectorized/console:master-173596f
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo 'testing'; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/console.yaml
    volumes:
      - type: bind
        source: ./
        target: /tmp
    ports:
      - "8080:8080"
    depends_on:
      - redpanda
```

**Comment by Shubham-Garg20** [comment]
@weeco, I updated the images to the latest release version which looks like this:

```
version: '2'
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.4
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 29092:29092

  console:
    image: docker.redpanda.com/redpandadata/console:v2.3.1
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo 'testing'; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/console.yaml
    volumes:
      - type: bind
        source: ./
        target: /tmp
    ports:
      - "8080:8080"
    depends_on:
      - redpanda
```

But I am still getting the same invalid keys error:

temp-console-1   | {"level":"fatal","msg":"failed to load yaml config","error":"failed to unmarshal YAML config into config struct: 1 error(s) decoding:\n\n* 'kafka.sasl.oauth' has invalid keys: clientId, clientSecret, scope, tokenEndpoint"}
