### ISSUE TITLE
Skip hidden dirs when loading Protos from filesystem

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#810]
Issue created by @smatvienko-tb:

              Hey, @weeco!
The proto-decoding feature is great!
The issue is still there. The files were imported twice in Kubernetes, and it was painful to map config map with many photos.

The problem and root cause are shown in the picture:
The **root cause** is **scanning hidden** folders.

![image](https://github.com/redpanda-data/console/assets/79898499/e33b9cdf-44fa-4795-bbad-c122e22176d5)

Steps to reproduce on any Linux environment:

1. Create a hidden folder `/tmp/protos/..data`
2. Put a proto file to the folder `/tmp/protos/..data/tbmsg.proto`
3. Make a symlink `/tmp/protos/tbmsg.proto` to `/tmp/protos/..data/tbmsg.proto`

```yaml
kafka:
  protobuf:
    enabled: true
    fileSystem:
      enabled: true
      paths:
        - /tmp/protos
```

The fix is to **avoid** scanning **hidden** files and folders (same as `ls` command do).

Otherwise, the Kubernetes deployment became painful. Some users might give up using the proto-decoding feature because of such an issue.

I am preparing the Redpanda console deployment for the [ThingsBoard IoT framework](https://thingsboard.io/) and I don't really want to submit a non-perfect deployment for a wide community. 
Unfortunately,  I can not help you with a good PR because it is not my language at this moment.
Let me know if you need to create a new issue.
Will be appreciated if you can implement the fix required for Kubernetes users 🙏 .

@pon0marev FYI

![image](https://github.com/redpanda-data/console/assets/79898499/cee255bf-5cda-4f82-8539-7af38b3af529)

_Originally posted by @smatvienko-tb in https://github.com/redpanda-data/console/issues/336#issuecomment-1677694488_

**Comment by smatvienko-tb** [comment]
Hey @weeco I tested that in the latest 2.3.2
and it can't parse the parameter
```
{"level":"fatal","msg":"failed to load yaml config","error":"failed to unmarshal YAML config into config struct: 1 error(s) decoding:\n\n* 'kafka.protobuf.FileSystem' has invalid keys: skipHiddenFiles"}
```

the yaml fragment
```
        fileSystem:
          enabled: true
          paths:
            - /protos
          refreshInterval: 1440m
          skipHiddenFiles: true
```

I guess the yaml mapping is missing in the source code similar to other fields:
![image](https://github.com/redpanda-data/console/assets/79898499/15896caa-8250-4b13-8a0c-7d2ec4762b25)

Could you please, make a fix?
