### ISSUE TITLE
Sasl authorisation

### ISSUE THREAD

**Issue by kpetravicius** [redpanda-data/console#851]
Deployment Details
A redpanda cluster was recently deployed on Kubernetes (k8s) using Helm (used documentation : https://docs.redpanda.com/current/deploy/deployment-option/self-hosted/kubernetes/). 

After deployment all cluster and console started-up. Added Ingress to get access to redpanda-console outside k8s. And everything was working.

But after SASL authentication was enabled with the following configuration:

```
tls:
  enabled: true
auth:
  sasl:
    enabled: true
    secretRef: redpanda-superusers
    users:
      - name: admin
        password: secret_pass
        mechanism: SCRAM-SHA-512
```

Console cannot access nothing. Shows **Backend API Error**. So its clear that console service (or pod?) has to get sasl user/password configuration.

Using rpk command line, created new user 'console-admin', added password 'console_admin_pass'. Added and acl with all privileges.  After that created new yaml file, to upgrade console (based on https://docs.redpanda.com/current/reference/redpanda-helm-spec/#console and https://artifacthub.io/packages/helm/redpanda-data/redpanda?modal=values&path=console):
```
console:
  config:
    kafka:
      sasl:
        enabled: true
        username: 'console-admin'
        password: 'console_admin_pass'
        mechanism: SCRAM-SHA-512
```

But problem stayed. Logs show:
```
{"level":"warn","ts":"2023-09-26T15:18:19.950Z","msg":"read from broker errored, killing connection after 0 successful responses (is SASL missing?)","source":"kafka_client","addr":"redpanda-1.redpanda.redpanda.svc.cluster.local.:9093","broker":"seed 1","err":"EOF"}
...
```

So where do I need to configure SASL for console service? Do I have to use ``kubectl edit ..`` and using editor enable sasl with  credentials or my console.config.kafka.sasl configuration is not in the right format?
